language: csharp
mono: none
dotnet: 2.0.0

install:
 - dotnet restore
 - curl -s https://codecov.io/bash > codecov
 - chmod +x codecov

script:
 - dotnet build
 - dotnet test tests/Yali.Tests/Yali.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - ./codecov -f tests/Yali.Tests/coverage.opencover.xml